# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Jeff Wray
title: Senior Full-Stack Developer
email: jeffwray@gmail.com
website: jeffwray.dev

# Social links
twitter_username: jeffwray
github_username:  jeffwray
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: jeffwray
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hello, my name’s Jeff, I’m a Senior Full-Stack Developer. As well as developing software, I have experience in managing remote development teams. I have extensive experience in delivering enterprise-ready web and mobile projects in the following industries: healthcare, hospitality, loyalty, oil/gas, entertainment, non-profits, and retail.
  I am most skilled in: <mark>API Development</mark>, <mark>Laravel</mark>, <mark>MySQL</mark>, <mark>Apache Cordova/PhoneGap</mark> and <mark>AWS</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
